draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: "auto"
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ''
  footer_text: ''
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}

parse_config:
  preprocess: true
  skip_binding_parsing: false
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  mark_alternate_layer_activators: false
  trans_legend:
    tap: ▽
    type: trans

  raw_binding_map:
    "MO(_NAVIGATION)": "NAV"
    "LT(_LOWER, KC_BSPC)":
      tap: $$mdi:backspace$$
      hold: LOWER
    "LT(_RAISE, KC_ENTER)":
      tap: $$mdi:keyboard-return$$
      hold: RAISE
    "LT(_NAVIGATION, KC_SPC)":
      tap: $$mdi:keyboard-space$$
      hold: NAV

  qmk_remove_keycode_prefix:
  - KC_
  - SC_

  # QMK
  qmk_keycode_map:
    # modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LCTL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    LCMD: $$mdi:apple-keyboard-command$$

    RCTRL: $$mdi:apple-keyboard-control$$
    RCTL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$
    RCMD: $$mdi:apple-keyboard-command$$

    # arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPC:
      type: space
      tap:  $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Space cadets
    SENT:
      tap: $$mdi:keyboard-esc$$
      hold: $$mdi:apple-keyboard-shift$$

    XXXXXXX: ''
    'NO': ''
    MINUS:
      tap: "-"
      shifted: "_"
    MINS: '-'
    EQUAL:
      tap: "="
      shifted: "+"
    EQL:
      tap: "="
      shifted: "+"
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH:
      tap: "/"
      shifted: "?"
    SLSH:
      tap: "/"
      shifted: "?"
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: ['AG']
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BLSH:
      tap: '\'
      shifted: "|"
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SCLN:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ':'
    QUOT:
      tap: "'"
      shifted: '"'
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA:
      tap: ","
      shifted: "<"
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT:
      tap: "."
      shifted: "<"
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC:
      tap: "["
      shifted: "{"
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC:
      tap: "]"
      shifted: "}"
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
