draw_config:
  key_w: 60.0
  key_h: 80

  # split_gap: 30.0

  # combo box dimensions
  combo_w: 36.0
  combo_h: 36.0

  # key border radius
  key_rx: 16
  key_ry: 16

  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # padding between keys
  inner_pad_w: 4
  inner_pad_h: 4

  # padding between layers
  outer_pad_w: 30.0
  outer_pad_h: 56.00

  line_spacing: 1.2
  # arc_radius: 6.0
  # append_colon_to_layer_header: true

  legend_rel_x: 0.0
  legend_rel_y: 0.0

  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4

  # footer_text: ''
  shrink_wide_legends: 5
  glyph_tap_size: 26
  glyph_hold_size: 18
  glyph_shifted_size: 18
  glyphs: {}

  # svg_extra_style:

parse_config:
  preprocess: true
  skip_binding_parsing: false
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  mark_alternate_layer_activators: false
  trans_legend:
    tap: ▽
    type: trans

  raw_binding_map:
    "NAV": "NAV"
    "LOWER":
      tap: $$mdi:backspace$$
      hold: LOWER
    "RAISE":
      tap: $$mdi:keyboard-return$$
      hold: RAISE
    "NAVSPC":
      tap: $$mdi:keyboard-space$$
      hold: NAV
    "LCTL_T(KC_ESC)":
      tap: $$mdi:keyboard-esc$$
      hold: $$mdi:apple-keyboard-control$$


  qmk_remove_keycode_prefix:
  - KC_
  - SC_

  # QMK
  qmk_keycode_map:
    # modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LCTL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    LCMD: $$mdi:apple-keyboard-command$$

    RCTRL: $$mdi:apple-keyboard-control$$
    RCTL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$
    RCMD: $$mdi:apple-keyboard-command$$

    # arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPC:
      type: space
      tap:  $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Space cadets
    SENT:
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:apple-keyboard-shift$$

    XXXXXXX: ''
    'NO': ''
    MINUS:
      tap: "-"
      shifted: "_"
    MINS: '-'
    EQUAL:
      tap: "="
      shifted: "+"
    EQL:
      tap: "="
      shifted: "+"
    LEFT_BRACKET: '['
    LBRC:
      tap: "["
      shifted: "{"
    RIGHT_BRACKET: ']'
    RBRC:
      tap: "]"
      shifted: "}"
    BACKSLASH: \
    BLSH:
      tap: '\'
      shifted: "|"
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SEMI:
      tap: ";"
      shifted: ":"
    SCLN:
      tap: ";"
      shifted: ":"
    QUOTE: ''''
    QUOT:
      tap: "'"
      shifted: '"'
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM:
      tap: ","
      shifted: "<"
    DOT:
      tap: "."
      shifted: ">"
    SLASH:
      tap: "/"
      shifted: "?"
    SLSH:
      tap: "/"
      shifted: "?"
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  # zmk_remove_keycode_prefix: ['AG']
  # zmk_keycode_map:
  #   EXCLAMATION: '!'
  #   EXCL: '!'
  #   AT_SIGN: '@'
  #   AT: '@'
  #   HASH: '#'
  #   POUND: '#'
  #   DOLLAR: $
  #   DLLR: $
  #   PERCENT: '%'
  #   PRCNT: '%'
  #   CARET: ^
  #   AMPERSAND: '&'
  #   AMPS: '&'
  #   ASTERISK: '*'
  #   ASTRK: '*'
  #   STAR: '*'
  #   LEFT_PARENTHESIS: (
  #   LPAR: (
  #   RIGHT_PARENTHESIS: )
  #   RPAR: )
  #   EQUAL: '='
  #   PLUS: +
  #   MINUS: '-'
  #   UNDERSCORE: _
  #   UNDER: _
  #   SLASH: /
  #   FSLH: /
  #   QUESTION: '?'
  #   QMARK: '?'
  #   BACKSLASH:
  #     tap: '\'
  #     shifted: "|"
  #   BLSH:
  #     tap: '\'
  #     shifted: "|"
  #   PIPE: '|'
  #   NON_US_BACKSLASH: \
  #   PIPE2: '|'
  #   NON_US_BSLH: '|'
  #   SEMICOLON:
  #     tap: ";"
  #     shifted: ":"
  #   SCLN:
  #     tap: ";"
  #     shifted: ":"
  #   SEMI:
  #     tap: ";"
  #     shifted: ":"
  #   COLON: ':'
  #   QUOT:
  #     tap: "'"
  #     shifted: '"'
  #   SINGLE_QUOTE:
  #     tap: "'"
  #     shifted: '"'
  #   SQT: ''''
  #   APOSTROPHE: ''''
  #   APOS: ''''
  #   DOUBLE_QUOTES: '"'
  #   DQT: '"'
  #   COMMA:
  #     tap: ","
  #     shifted: "<"
  #   LESS_THAN: <
  #   LT: <
  #   PERIOD: .
  #   DOT:
  #     tap: "."
  #     shifted: "<"
  #   GREATER_THAN: '>'
  #   GT: '>'
  #   LEFT_BRACKET: '['
  #   LBKT: '['
  #   LEFT_BRACE: '{'
  #   LBRC:
  #     tap: "["
  #     shifted: "{"
  #   RIGHT_BRACKET: ']'
  #   RBKT: ']'
  #   RIGHT_BRACE: '}'
  #   RBRC:
  #     tap: "]"
  #     shifted: "}"
  #   GRAVE: '`'
  #   TILDE: '~'
  #   NON_US_HASH: '#'
  #   NUHS: '#'
  #   TILDE2: '~'
  # zmk_combos: {}
